---
apiVersion: v1
kind: Service
metadata:
  name: ws-frontend-svc-cip
  namespace: ingress-nginx
spec:
  selector:
    app: ws-frontend
  type: ClusterIP
  ports:
  - name: ws-frontend
    protocol: TCP
    port: 80
    targetPort: 80