---
apiVersion: v1
kind: Service
metadata:
  name: ws-backend-svc-cip
  namespace: ingress-nginx
spec:
  selector:
    app: ws-backend
  type: ClusterIP
  ports:
  - name: ws-backend
    protocol: TCP
    port: 8080
    targetPort: 8080